kind: pipeline
type: exec
name: default

clone:
  disable: true

platform:
  os: linux
  ar—Åh: amd64

steps:
- name: Reload oToDo
  commands:
    - cd /home/ss/src/oToDo
    - git pull origin main
    - killall otodo
    - nohup go run ./