kind: pipeline
type: exec
name: default

clone:
  disable: true

platform:
  os: linux
  ar—Åh: amd64

steps:
- name: Run Commands
  commands:
    - export ALL_PROXY=http://127.0.0.1:10809
    - cd /home/ss/src/oToDo
    - sudo git pull
    - sudo killall otodo
    - sudo nohup go run ./